output: web

topnav_title: Werf Documentation
site_title: Werf Documentation
company_name: Flant
url: https://werf.io
sitemap_urls:
  ru:
    url: ru.werf.io
  en:
    url: werf.io

exclude:
- .idea/
- .gitignore
- vendor

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: false
 hard_wrap: false
 syntax_highlighter: rouge

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text
  hometext: "Home"

collections:
  tooltips:
    output: false

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      lang: en
      comments: true
      search: true
      sidebar: sidebar
      topnav: topnav
  - scope:
      path: "pages_ru"
      type: "pages"
    values:
      lang: ru


sidebars:
- documentation

