output: web

topnav_title: Werf Documentation
site_title: Werf Documentation
company_name: Flant
url: https://werf.io

exclude:
- .idea/
- .gitignore
- vendor

highlighter: rouge

markdown: kramdown
kramdown:
 input: GFM
 auto_ids: false
 hard_wrap: false
 syntax_highlighter: rouge

breadcrumbs:
  root:
    hide: false  # show breadcrumbs on root/home page
    image: false # Show image or title text

collections:
  tooltips:
    output: false

defaults:
- scope:
    path: ""
    type: "pages"
  values:
    layout: "page"
    lang: en
    comments: true
    search: true
    sidebar: sidebar
    topnav: topnav

sidebars:
- documentation

t:
  en:
    breadcrumbs:
      home: "Home"
  ru:
    breadcrumbs:
      home: "Начало"
